### ISSUE TITLE
Local installation

### ISSUE THREAD

**Issue by karussell** [perliedman/lrm-graphhopper#1]
Hi, thanks a lot for this work! Is it possible to use this against a local installation too? From the readme it looks it supports only the Directions API. Which is of course nice, but there might be demand for a local installation too.

**Comment by perliedman** [comment]
Yes, good point. Documentation is lacking, but it is possible through options to the constructor:

``` js
L.Routing.control({
    router: new L.Routing.GraphHopper('your GraphHopper API key', {
        serviceUrl: 'http://your-own-instance/'
    }),
}).addTo(map);
```

`serviceUrl` otherwise defaults to `'https://graphhopper.com/api/1/route'`

Will add this once I get to do a more complete readme/docs.

**Comment by karussell** [comment]
Ah, ok!
