### ISSUE TITLE
Graphhopper credit headers

### ISSUE THREAD

**Issue by opoto** [perliedman/lrm-graphhopper#15]
Graphhopper responses contain valuable credit information in http response headers: X-RateLimit-Remaining, X-RateLimit-Credits, X-RateLimit-Reset... Could lrm-graphhopper pass this information to the application, eg through an event the application would listen to?

**Comment by perliedman** [comment]
@opoto hm, interesting. I guess one way would be for the router class to extend `Evented` and emit events when a response is received, which could include response headers.

I'm not actively using lrm-graphhopper myself, so it's not likely I will add this functionality myself, but a pull request would be most welcome!

**Comment by opoto** [comment]
I will give it a try.

**Comment by opoto** [comment]
Waiting for @graphhopper to properly handle CORS requests

**Comment by opoto** [comment]
Pull request #16

**Comment by perliedman** [comment]
Closed from merging #16 :tada:
