### ISSUE TITLE
Clarify which options are suported by lrm-graphhopper

### ISSUE THREAD

**Issue by sanastasiou** [perliedman/lrm-graphhopper#17]
Hi and thanks for this nice plugin. 

I am playing with it a little bit, but I find the lack of documentation a bit confusing.

For example, retrieving gpx data will lead to plugin crash, so will elevation option. I haven't tried other features from graphhopper api so I don't know if the rest of the options work.

Could you please make a list of which options from the routing api are available, if any so that we know what the plugin supports?

Many thanks!

**Comment by perliedman** [comment]
Hi,
basically any option that alters the format of the returned route(s) will not work: GPX for example will use a different format than the compressed polyline that the plugin uses and expects. I'm not familiar with the elevation option, but I suspect it leads to similar problems.

I should say that I'm not actively using this plugin, or GraphHopper, myself, so I don't have such a list handy, and couldn't easily make one.

It should be fairly straight forward to alter the plugin to work with most options, there isn't that much code involved.

**Comment by sanastasiou** [comment]
Thanks for the reply!
