### ISSUE TITLE
in_same_route or in_sequence?

### ISSUE THREAD

**Issue by VanDerLars** [perliedman/lrm-graphhopper#18]
is it possible to use in_same_route or in_sequence? Or How can I add that?

**Comment by perliedman** [comment]
Not sure what those are, but if they are URL parameters to GraphHopper, you can use the `urlParameters` option to specify additional URL parameters to the request:

```js
var router = L.Routing.graphHopper({
    urlParameters: {
        in_same_route: x,
        in_sequence: y
    }
});
```
