### ISSUE TITLE
Roundabout

### ISSUE THREAD

**Issue by karussell** [perliedman/lrm-graphhopper#2]
Hi, the latest API (which we'll release in a few hours) will contain a new instruction 'roundabout'. See  [here](https://github.com/graphhopper/graphhopper/blob/master/docs/web/api-doc.md#example-output-for-the-case-typejson) and the 'sign'

**Comment by perliedman** [comment]
Thanks for the heads up! Added in 511355118efdb6a4b8948320b0d90a215621f604.
