### ISSUE TITLE
Adding the optimize to true for reordering waypoints.

### ISSUE THREAD

**Issue by yoann54** [perliedman/lrm-graphhopper#30]
I'm trying to add th optimize true option as described here https://docs.graphhopper.com/#operation/getRoute. 

`var routingControl = L.Routing.control({
        router: new L.Routing.GraphHopper(process.env.GRAPHHOPPER_KEY),
        optimize: true,
        waypoints: this.waypoints,
        lineOptions: {
          styles: [{ color: "orange", opacity: 1, weight: 6 }]
        }
      });`

Routing line s added to my maps but the optimize=true is not in the query. How can i do that ?

**Comment by perliedman** [comment]
You can use the `urlParameters` option if you need to add parameters to the query string.
