### ISSUE TITLE
Hi, help with service url parameters

### ISSUE THREAD

**Issue by DanielShinken** [perliedman/lrm-graphhopper#8]
Hi there, I would like to know if there's a way to send parameters such as locale, optimize, etc through this plugin, I'm using it like this.

router: L.Routing.graphHopper('<my api key>'),

but I would like to change the instruction's language and add more parameters, how can we achieve that?, thanks and greetings

**Comment by perliedman** [comment]
Hi!

There is an option for the `L.Routing.GraphHopper` class called `urlParameters`: it is a hash of parameters that will be added to the URL of each request to the server. You can use it like this, for example:

``` javascript
new L.Routing.GraphHopper('myKey', {urlParameters: {vehicle: 'foot'}})
```

Hope this helps!

**Comment by DanielShinken** [comment]
awesome! thank! awesome plugin!
