### ISSUE TITLE
Get path total time with lrm graphhopper

### ISSUE THREAD

**Issue by lapaseb** [perliedman/lrm-graphhopper#9]
Hello, I would like to know how to get the total time of a path with lrm-graphhopper.js 

Here is my code :

``` javascript
var routeControl = L.Routing.control({
    waypoints: [
        L.latLng(position.coords.latitude, position.coords.longitude),
        L.latLng($scope.markers[$stateParams.mapId].lat, $scope.markers[$stateParams.mapId].lng)
    ],
    draggableWaypoints: false,
    addWaypoints: false,
    routeWhileDragging: false,
    router: L.Routing.graphHopper('apiKey', {urlParameters: {vehicle: 'foot'}})

}).addTo(map);
```

This will draw the path between the user's position and the position of a place on the map.
I would like to show to the user how much time this will need to do this.

I saw in lrm-graphhopper.js file that there is `path.distance` and `path.time`, but I don't know how to access them.

Thanks in advance
Best regards
Sébastien

**Comment by perliedman** [comment]
Hi!

This is basically the same problem as this Leaflet Routing Machine issue: https://github.com/perliedman/leaflet-routing-machine/issues/150

In essence, you want to either:
- use `L.Routing.GraphHopper` directly if you're not interested in the control's user interface
- listen for events from `L.Routing.Control` if you need the user interface, but also want to get the route alternatives when they're calculated

**Comment by lapaseb** [comment]
Thank you for your answer. It works perfectly.

I looked at your issue link, and I found the answer there. Here is my code :

```
routeControl.on('routesfound', function(e) {
      var routes = e.routes;
      alert(routes[0].summary.totalTime / 60 + ' minute(s).');
});
```

Thank you again, have a nice day

**Comment by perliedman** [comment]
Exactly, that's the solution.

It's on my todo to write a tutorial on this some time, since it's a pretty common question.
